# Generated by Django 4.2.11 on 2024-04-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Oder",
            new_name="Order",
        ),
        migrations.RenameModel(
            old_name="OderItem",
            new_name="OrderItem",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="dat_oder",
            new_name="dat_order",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="oder",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="shippingaddress",
            old_name="oder",
            new_name="order",
        ),
    ]
